services:
  - type: web
    name: needhgolderpbackend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: NODE_ENV
        value: production
    buildpacks:
      - url: heroku/nodejs